DROP TABLE IF EXISTS DRANKS;

CREATE TABLE IF NOT EXISTS DRANKS(
id SERIAL PRIMARY KEY,
barname VARCHAR (255),
address VARCHAR(255),
zipcode INTEGER,
phone_number INTEGER,
bartype VARCHAR (255),
cost INTEGER)

CREATE INDEX ON DRANKS (author);